default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default
  channel_prefix: development

test:
  <<: *default
  channel_prefix: test

production:
  <<: *default
  channel_prefix: production
